Aula13/EfContaLuz/Models/ErrorViewModel.cs
using System;

namespace EfContaLuz.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Aula13/EfContaLuz/Controllers/ContaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EfContaLuz.Models;

namespace EfContaLuz.Controllers
{
    public class ContaController : Controller
    {
         
        private IContaRepository repository;
        public ContaController(IContaRepository repository)
        {
            this.repository = repository;
        }
        public IActionResult Index()
        {      
            return View(new ContaView(repository));
          
        }

        public IActionResult Create()
        {
            
            return View();
        }

        [HttpPost]
         public IActionResult Create(Conta c)
        {
            c.imovel= new Imovel{id=1, numero=2, descricao="oi", cidade="Torres", estado="RS"};
           repository.Create(c);
            return RedirectToAction("Index");
        }

         public IActionResult Edit(int id)
        {
            var conta = repository.GetById(id);
            return View(conta);
        }

        [HttpPost]
         public IActionResult Edit(Conta c)
        {
           repository.Update(c);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            repository.Delete(id);
            return RedirectToAction("Index");

        }

       
       
    }
}

Aula13/EfContaLuz/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EfContaLuz.Models;

namespace EfContaLuz.Controllers
{
    public class HomeController : Controller
    {
        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Aula13/EfContaLuz/Views/Conta/Create.cshtml
@model EfContaLuz.Models.Conta

<div class="form-horizontal">
    <form action="Create" method="Post">

        <div class="form-group">
            <label>Id</label>
            <input  class="form-control"
                    type="text" name="id"/>
        </div>

        <div class="form-group">
            <label>Nome</label>
            <input  class="form-control"
                    type="text" name="nome"/>
        </div>

        <div class="form-group">
            <label>Numero Leitura</label>
            <input  class="form-control"
                    type="text" name="numLeitura"/>
        </div>
         <div class="form-group">
            <label>kw Gasto</label>
            <input  class="form-control"
                    type="text" name="kwGasto"/>
        </div>
         <div class="form-group">
            <label>Valor Pagar</label>
            <input  class="form-control"
                    type="text" name="valorPagar"/>
        </div>
         <div class="form-group">
            <label>Data Pagamento</label>
            <input  class="form-control"
                    type="text" name="dataPagamento"/>
        </div>
         <div class="form-group">
            <label>Media Consumo</label>
            <input  class="form-control"
                    type="text" name="mediaConsumo"/>
        </div>


        <input  class="btn btn-primary" 
                type="submit" value="Salvar"/>

    </form>
</div>

Aula13/EfContaLuz/Views/Conta/Edit.cshtml
@model EfContaLuz.Models.Conta

<div class="form-horizontal">
    <form action="Edit" method="Post">

        <div class="form-group">
            <label>Id</label>
            <input  class="form-control"
                    type="text" name="id"
                    value = "@Model.id"/>
        </div>

        <div class="form-group">
            <label>Nome</label>
            <input  class="form-control"
                    type="text" name="nome"      value="@Model.nome"/>
        </div>

        <div class="form-group">
            <label>Numero Leitura</label>
            <input  class="form-control"
                    type="text" name="numLeitura"
                    value = "@Model.numLeitura"/>
        </div>
        <div class="form-group">
            <label>kw Gasto</label>
            <input  class="form-control"
                    type="text" name="kwGasto"
                    value = "@Model.kwGasto"/>
        </div>
        <div class="form-group">
            <label>Valor Pagar</label>
            <input  class="form-control"
                    type="text" name="valorPagar"
                    value = "@Model.valorPagar"/>
        </div>
        <div class="form-group">
            <label>Data Pagamento</label>
            <input  class="form-control"
                    type="text" name="dataPagamento"
                    value = "@Model.dataPagamento"/>
        </div>
        <div class="form-group">
            <label>Media Consumo</label>
            <input  class="form-control"
                    type="text" name="mediaConsumo"
                    value = "@Model.mediaConsumo"/>
        </div>


        <input  class="btn btn-primary" 
                type="submit" value="Salvar"/>

    </form>
</div>

Aula13/EfContaLuz/Views/Conta/Index.cshtml
@model EfContaLuz.Models.ContaView

    
</br></br>
<a href="Conta/Create" class="btn btn-primary">Nova Pessoa</a>
</br></br>

<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>numero Leitura</th>
                <th>kwGasto</th>
                <th>Valor Pagar</th>
                <th>Data Pagamento</th>
                <th>Media Consumo</th>
                <th>Numero</th>
                <th>Descricao</th>
                <th>Cidade</th>
                <th>Estado</th>
                <th></th>
                <th></th>
            </tr>
        </thead>

        @foreach(var item in Model.lista)
        {
            <tr>
                <td>@item.id</td>
                <td>@item.nome</td>
                <td>@item.numLeitura</td>
                <td>@item.kwGasto</td>
                <td>@item.valorPagar</td>
                <td>@item.dataPagamento</td>
                <td>@item.mediaConsumo</td>
                <td>@item.imovel.numero</td>
                <td>@item.imovel.descricao</td>
                <td>@item.imovel.cidade</td>
                <td>@item.imovel.estado</td>
                <td><a class="btn btn-danger"
                    href="Conta/Delete/@item.id">Delete</a> </td>
                <td><a class="btn btn-primary" 
                    href="Conta/Edit/@item.id">Editar</a> </td>
            </tr>
        }
        
    </table>


      @if(Model.lista.Any())
        {
            <h3>Tabela de MENOR Consumo</h3>
        <table class="table" border="5">
            <tr>
                <td>id</td>
                <td>Nome</td>
                <td>Numero Leitura</td>
                <td>kw Gasto</td>
                <td>valor Pagar</td>
                <td>data Pagamento</td>
                <td>Media Consumo</td>
            </tr>
            <tr>

                    <td>@Model.menorConsumo.id</td>
                    <td>@Model.menorConsumo.nome</td>
                    <td>@Model.menorConsumo.numLeitura</td>
                    <td>@Model.menorConsumo.kwGasto</td>
                    <td>@Model.menorConsumo.valorPagar</td>
                    <td>@Model.menorConsumo.dataPagamento</td>
                     <td>@Model.menorConsumo.mediaConsumo</td>
                     </tr>
        </table>
        }
        
        <br>



         @if(Model.lista.Any())
        {
            <h3>Tabela de MAIOR Consumo</h3>
        <table  class="table" border="5">
            <tr>
                <td>id</td>
                <td>Nome</td>
                <td>Numero Leitura</td>
                <td>kw Gasto</td>
                <td>valor Pagar</td>
                <td>data Pagamento</td>
                <td>Media Consumo</td>
            </tr>
            <tr>

                    <td>@Model.maiorConsumo.id</td>
                    <td>@Model.maiorConsumo.nome</td>
                    <td>@Model.maiorConsumo.numLeitura</td>
                    <td>@Model.maiorConsumo.kwGasto</td>
                    <td>@Model.maiorConsumo.valorPagar</td>
                    <td>@Model.maiorConsumo.dataPagamento</td>
                     <td>@Model.maiorConsumo.mediaConsumo</td>
                     </tr>
        </table>
        }
</div>

Aula13/EfContaLuz/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Aula13/EfContaLuz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EfContaLuz</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EfContaLuz</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Conta" asp-action="Index">Conta</a>
                        </li>
                    
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - EfContaLuz - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>